# Generated by Django 6.1.1 on 2026-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('ADMIN', 'admin')], default='CUSTOMER', max_length=10),
        ),
    ]
