# Generated by Django 6.1.1 on 2026-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_version',
        ),
        migrations.AddField(
            model_name='user',
            name='token_verified',
            field=models.BooleanField(default=False),
        ),
    ]
