# Generated by Django 6.1.1 on 2026-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='sold_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
