# Generated by Django 6.1.1 on 2026-09-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0002_alter_flashsale_reserved_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsale',
            old_name='allocated_stock',
            new_name='allocate_stock',
        ),
    ]
