# Generated by Django 6.1.1 on 2026-09-19 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_slug'),
        ('flash_sales', '0003_rename_allocated_stock_flashsale_allocate_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flash_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocate_stock', models.PositiveIntegerField()),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('sold_stock', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SOLD_OUT', 'SOLD_OUT'), ('SCHEDULED', 'SCHEDULED'), ('ACTIVE', 'ACTIVE'), ('ENDED', 'ENDED')], default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Flash_sales', to='catalog.product')),
            ],
        ),
        migrations.DeleteModel(
            name='FlashSale',
        ),
    ]
