# Generated by Django 6.1.1 on 2026-09-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0004_flashsaleitem_delete_flashsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsaleitem',
            name='allocate_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
