# Generated by Django 6.1.1 on 2026-09-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0005_alter_flashsaleitem_allocate_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsaleitem',
            old_name='end_date',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='flashsaleitem',
            old_name='start_date',
            new_name='start_date_time',
        ),
    ]
