# Generated by Django 6.1.1 on 2026-09-19 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expires_at_alter_order_flash_sale_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.TimeField(db_index=True, default=datetime.datetime(2026, 9, 19, 7, 57, 48, 296498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
