# Generated by Django 6.1.1 on 2026-09-19 07:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_expires_at_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.TimeField(db_index=True, default=datetime.datetime(2026, 9, 19, 7, 58, 43, 511679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
