# Generated by Django 6.1.1 on 2026-09-20 11:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0005_alter_flashsaleitem_allocate_stock'),
        ('orders', '0007_alter_order_expires_at_alter_order_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_user_flash_sale_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 9, 20, 11, 29, 13, 440507, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'EXPIRED'), _negated=True), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('user', 'flash_sale_item'), name='unique_user_flash_sale_item'),
        ),
    ]
