# Generated by Django 6.1.1 on 2026-09-20 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_unique_user_flash_sale_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 9, 20, 11, 36, 38, 829498, tzinfo=datetime.timezone.utc)),
        ),
    ]
