# Generated by Django 6.1.1 on 2026-09-22 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 9, 22, 1, 40, 24, 560649, tzinfo=datetime.timezone.utc)),
        ),
    ]
